version: '3'

services:
    irods-catalog:
        build:
            context: irods_catalog
        # 5432 is exposed by default and can conflict with other postgres containers.
        # When the metalnx-db service is no longer needed, this stanza can be removed.
        ports:
            - "5430:5432"
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-provider:
        build:
            context: irods_catalog_provider
        shm_size: 500mb
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "ils || exit 1"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 2s
        ports:
            - "1247:1247"
        depends_on:
            - irods-catalog

